USE master
CREATE DATABASE QLNhanVien
GO

USE QLNhanVien
GO

CREATE TABLE DiaChi (
    MaDC INT IDENTITY(1,1) PRIMARY KEY,
    DiaChi1 NVARCHAR (200) DEFAULT NULL,
    DiaChi2 NVARCHAR (200) DEFAULT NULL,
    ThanhPho NVARCHAR (30) NOT NULL,
)
GO
 
CREATE TABLE CapBac (
    MaCB INT IDENTITY(1,1) PRIMARY KEY,
    TenCB NVARCHAR (35) NOT NULL,
    MinLuong DECIMAL (8, 2) DEFAULT NULL,
    MaxLuong DECIMAL (8, 2) DEFAULT NULL
)
GO
 
CREATE TABLE PhongBan (
    MaPB INT IDENTITY(1,1) PRIMARY KEY,
    TenPB NVARCHAR (30) NOT NULL,
    MaTP INT DEFAULT NULL,
    NG_NHANCHUC DATETIME DEFAULT(GETDATE())
)
GO
 
CREATE TABLE NhanVien (
    MaNV INT IDENTITY(1,1) PRIMARY KEY,
    HoNV NVARCHAR (20) DEFAULT NULL,
    TenNV NVARCHAR (25) NOT NULL,
    email NVARCHAR (100) NOT NULL,
    SDT NVARCHAR (20) DEFAULT NULL,
    NgayThue DATE NOT NULL,
    MaCB INT NOT NULL,
    Luong DECIMAL (8, 2) NOT NULL,
    MaPB INT DEFAULT NULL,
    MaDC INT DEFAULT NULL
    FOREIGN KEY (MaCB) REFERENCES CapBac (MaCB) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MaPB) REFERENCES PhongBan (MaPB) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MaDC) REFERENCES DiaChi (MaDC) ON DELETE CASCADE ON UPDATE CASCADE,
)
GO
 
CREATE TABLE ThanNhan (
    MaTN INT IDENTITY(1,1) PRIMARY KEY,
    HoTN NVARCHAR (50) NOT NULL,
    TenTN NVARCHAR (50) NOT NULL,
    TenQuanHe NVARCHAR (25) NOT NULL,
    MaNV INT NOT NULL,
    FOREIGN KEY (MaNV) REFERENCES NhanVien (MaNV) ON DELETE CASCADE ON UPDATE CASCADE
)
GO